# Generated by Django 3.0.3 on 2020-11-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20201108_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('PB', 'Publish'), ('UPB', 'Unpublish')], default='PB', max_length=5),
        ),
    ]
