# Generated by Django 3.0.3 on 2020-12-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_post_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('referer', models.CharField(blank=True, default='Choose', max_length=10)),
                ('gender', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
